// src/pages/HomePage.tsx
import type { Story } from '@/lib/types'
import { IonButton, IonButtons, IonContent, IonHeader, IonIcon, IonInfiniteScroll, IonInfiniteScrollContent, IonList, IonPage, IonRefresher, IonRefresherContent, IonSpinner, IonTitle, IonToolbar } from '@ionic/react'
import { useInfiniteQuery } from '@tanstack/react-query'
import { logoGithub } from 'ionicons/icons'
import { ofetch } from 'ofetch'
import { Fragment } from 'react'
import StoryListing from '@/components/StoryListing'

export default function HomePage() {
  async function fetchStories({ pageParam }: { pageParam: unknown }) {
    return await ofetch(`https://node-hnapi.herokuapp.com/news?page=${pageParam}`)
  }

  const { isPending, data, refetch, fetchNextPage } = useInfiniteQuery<Story[]>({
    queryKey: ['stories'],
    queryFn: fetchStories,
    initialPageParam: 1,
    getNextPageParam: (_, allPages) => allPages.length + 1,
  })

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonButtons slot="end">
            <IonButton
              href="https://github.com/tijnjh/hn"
              target="_blank"
            >
              <IonIcon icon={logoGithub} />
            </IonButton>
          </IonButtons>
          <IonTitle>Frontpage</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent fullscreen>
        <IonRefresher
          slot="fixed"
          onIonRefresh={async (e) => {
            await refetch()
            e.detail.complete()
          }}
        >
          <IonRefresherContent />
        </IonRefresher>

        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Frontpage</IonTitle>
          </IonToolbar>
        </IonHeader>

        {isPending && <IonSpinner className="my-8 w-full" />}

        <IonList>
          {data?.pages.map(stories => (
            <Fragment key={stories[0].id}>
              {stories.map(story => (
                <StoryListing key={story.id} story={story} />
              ))}
            </Fragment>
          ))}
        </IonList>

        <IonInfiniteScroll
          onIonInfinite={(e) => {
            fetchNextPage().finally(() => {
              e.target.complete()
            })
          }}
          threshold="100px"
        >
          <IonInfiniteScrollContent />
        </IonInfiniteScroll>
      </IonContent>
    </IonPage>
  )
}

// src/pages/HomePage.vue
<script setup lang="ts">
import StoryListing from "../lib/components/StoryListing.vue";
import {
  IonContent,
  IonHeader,
  IonList,
  IonPage,
  IonTitle,
  IonToolbar,
  IonInfiniteScroll,
  IonInfiniteScrollContent,
  IonRefresher,
  IonRefresherContent,
  IonSpinner,
  IonButtons,
  IonButton,
  IonIcon,
  InfiniteScrollCustomEvent,
  RefresherCustomEvent,
} from "@ionic/vue";
import { logoGithub } from "ionicons/icons";
import { Story } from "../lib/types";
import { ref } from "vue";
import { onMounted } from "vue";

const STORIES_PER_PAGE = 25;

async function fetchStoryIds(page: number, storiesPerPage: number) {
  const url = "https://hacker-news.firebaseio.com/v0/topstories.json";
  const response = await (await fetch(url)).json();
  const start = (page - 1) * storiesPerPage;
  return response.slice(start, start + storiesPerPage);
}

async function fetchStories(ids: number[]) {
  const baseUrl = "https://hacker-news.firebaseio.com/v0/item/";
  const fetchPromises = ids.map((id) =>
    fetch(`${baseUrl}${id}.json`).then((res) => res.json()),
  );
  return Promise.all(fetchPromises);
}

async function loadStories(page: number) {
  try {
    const storyIds = await fetchStoryIds(page, STORIES_PER_PAGE);
    const fetchedStories = await fetchStories(storyIds);
    stories.value = [...stories.value, ...fetchedStories];
  } catch (error) {
    console.error("Failed to load stories:", error);
  } finally {
    showInitialSpinner.value = false;
  }
}

function handleRefresh(event: RefresherCustomEvent) {
  page.value = 1;
  stories.value = [];
  loadStories(1).then(() => {
    event.detail.complete();
  });
}

function loadMore(event: InfiniteScrollCustomEvent) {
  page.value++;
  loadStories(page.value + 1).then(() => {
    event.target.complete();
  });
}

const stories = ref<Story[]>([]);
const page = ref(1);
const showInitialSpinner = ref(true);

onMounted(() => {
  loadStories(page.value);
});
</script>

<template>
  <ion-page id="home-page">
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="end">
          <ion-button href="https://github.com/tijnjh/hn">
            <ion-icon :icon="logoGithub" slot="icon-only" />
          </ion-button>
        </ion-buttons>
        <ion-title>Frontpage</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content fullscreen>
      <ion-refresher slot="fixed" @ion-refresh="handleRefresh">
        <ion-refresher-content />
      </ion-refresher>
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Frontpage</ion-title>
        </ion-toolbar>
      </ion-header>

      <ion-spinner v-if="showInitialSpinner" class="initial-spinner" />

      <ion-list>
        <StoryListing v-for="story in stories" :key="story.id" :story="story" />
      </ion-list>

      <ion-infinite-scroll @ion-infinite="loadMore" threshold="100px">
        <ion-infinite-scroll-content></ion-infinite-scroll-content>
      </ion-infinite-scroll>
    </ion-content>
  </ion-page>
</template>

<style scoped>
.initial-spinner {
  width: 100%;
  margin-block-start: 2rem;
}
</style>
