// src/pages/StoryPage.vue
<script setup lang="ts">
import {
  IonAvatar,
  IonBackButton,
  IonButton,
  IonButtons,
  IonContent,
  IonHeader,
  IonIcon,
  IonItem,
  IonLabel,
  IonList,
  IonPage,
  IonSpinner,
  IonText,
  IonToolbar,
} from "@ionic/vue";

import { arrowUp, chevronDown, chevronUp, openOutline } from "ionicons/icons";
import { computed, ref } from "vue";
import { useRoute } from "vue-router";
import { formatUrl, relativify } from "../lib/utils";
import { Story } from "../lib/types";

const route = useRoute();

async function fetchStory(id: number) {
  const url = `https://node-hnapi.herokuapp.com/item/${id}`;
  const response = await (await fetch(url)).json();
  return response;
}

const story = ref<Story>();
const collapsedThreads = ref<Set<number>>(new Set());
const loading = ref<boolean>(true);

async function loadStory(id: number) {
  loading.value = true;
  const storyData = await fetchStory(id);
  story.value = storyData;
  loading.value = false;
}

loadStory(Number(route.params.id));

function toggleCollapse(commentId: number) {
  const newSet = new Set(collapsedThreads.value);
  if (newSet.has(commentId)) {
    newSet.delete(commentId);
  } else {
    newSet.add(commentId);
  }
  collapsedThreads.value = newSet;
}

const isExternalLink = computed(() => story.value?.url?.startsWith("http"));
</script>

<template>
  <ion-page>
    <ion-header translucent>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button text="Frontpage" default-href="/"></ion-back-button>
        </ion-buttons>

        <ion-buttons slot="end">
          <ion-button v-if="isExternalLink" :href="story?.url" target="_blank">
            {{ formatUrl(story?.url!) }}
            <ion-icon slot="end" :icon="openOutline"></ion-icon>
          </ion-button>
        </ion-buttons>
      </ion-toolbar>
    </ion-header>

    <ion-content color="light">
      <ion-spinner
        v-if="loading"
        style="width: 100%; margin-block-start: 2rem"
      />

      <template v-if="story">
        <ion-list style="margin-bottom: 0.5rem">
          <ion-item
            :href="isExternalLink ? story.url! : undefined"
            target="_blank"
          >
            <ion-avatar
              aria-hidden="true"
              slot="start"
              style="--border-radius: 0.25rem"
            >
              <img
                alt=""
                :src="`https://www.google.com/s2/favicons?domain=${story.url}&sz=64`"
              />
            </ion-avatar>
            <ion-label>
              <h2>{{ story.title }}</h2>
              <h3 style="display: flex; align-items: center">
                {{ story.points }}
                <ion-icon :icon="arrowUp" />
                <span style="margin-inline: 0.5rem">&bull;</span>
                <span style="flex-shrink: 0">{{ relativify(story.time) }}</span>
                <template v-if="isExternalLink">
                  <span style="margin-inline: 0.5rem">&bull;</span>
                  <span
                    style="white-space: nowrap; text-overflow: ellipsis; overflow: hidden"
                  >
                    {{ formatUrl(story.url) }}
                  </span>
                </template>
              </h3>
            </ion-label>
          </ion-item>
        </ion-list>

        <ion-list
          v-for="comment in story.comments"
          :key="comment.id"
          style="margin-bottom: 0.5rem"
        >
          <ion-item>
            <ion-label>
              <p
                @click="toggleCollapse(comment.id)"
                style="display: flex; align-items: center; cursor: pointer"
              >
                {{ comment.user }}
                <span style="margin-inline: 0.5rem">&bull;</span>
                {{ relativify(comment.time) }}
                <span style="margin-left: auto">
                  <ion-icon
                    v-if="!collapsedThreads.has(comment.id)"
                    :icon="chevronUp"
                  />
                  <ion-icon v-else :icon="chevronDown" />
                </span>
              </p>
              <div
                class="comment-content"
                :class="
                  {
                    collapsed: collapsedThreads.has(comment.id),
                    expanded: !collapsedThreads.has(comment.id),
                  }
                "
              >
                <ion-text>
                  <div v-html="comment.content"></div>
                </ion-text>
              </div>
            </ion-label>
          </ion-item>
          <template v-if="!collapsedThreads.has(comment.id)">
            <ion-item
              v-for="reply in comment.comments"
              :key="reply.id"
              :style="{ paddingLeft: `${reply.level}rem` }"
            >
              <ion-label>
                <p style="display: flex; align-items: center">
                  {{ reply.user }}
                  <span style="margin-inline: 0.5rem">&bull;</span>
                  {{ relativify(reply.time) }}
                </p>

                <div
                  class="comment-content"
                  :class="
                    {
                      collapsed: collapsedThreads.has(
                        comment.id,
                      ),
                      expanded: !collapsedThreads.has(
                        comment.id,
                      ),
                    }
                  "
                >
                  <ion-text>
                    <div v-html="reply.content"></div>
                  </ion-text>
                </div>
              </ion-label>
            </ion-item>
          </template>
        </ion-list>
      </template>
      <template v-else>
        <p></p>
      </template>
    </ion-content>
  </ion-page>
</template>

<style scoped>
.comment-content {
  transition: height 0.3s ease;
  overflow: hidden;
}

.comment-content.collapsed {
  height: 0;
}

.comment-content.expanded {
  height: calc-size(max-content, size);
}
</style>

// src/pages/StoryPage.tsx
import type { Comment, Story } from "@/lib/types";
import { formatUrl, relativify } from "@/lib/utils";
import {
    IonAvatar,
    IonBackButton,
    IonButton,
    IonButtons,
    IonContent,
    IonHeader,
    IonIcon,
    IonItem,
    IonLabel,
    IonList,
    IonPage,
    IonSpinner,
    IonText,
    IonToolbar,
} from "@ionic/react";
import { useQuery } from "@tanstack/react-query";
import { arrowUp, chevronDown, chevronUp, openOutline } from "ionicons/icons";
import { haptic } from "ios-haptics";
import { ofetch } from "ofetch";
import { useState } from "react";

interface StoryPageProps {
    match: {
        params: {
            id: string;
        };
    };
}

export default function StoryPage({ match: { params } }: StoryPageProps) {
    const [collapsedThreads, setCollapsedThreads] = useState<Set<number>>(
        new Set(),
    );

    function toggleCollapse(commentId: number) {
        haptic();
        const newSet = new Set(collapsedThreads);

        if (newSet.has(commentId)) {
            newSet.delete(commentId);
        } else {
            newSet.add(commentId);
        }
        setCollapsedThreads(newSet);
    }
    const url = `https://node-hnapi.herokuapp.com/item/${params.id}`;

    const { isPending, data: story } = useQuery<Story>({
        queryKey: [`story-${params.id}`],
        queryFn: () => ofetch(url),
    });

    const isExternalLink = story?.url?.startsWith("http");

    return (
        <IonPage>
            <IonHeader translucent>
                <IonToolbar>
                    <IonButtons slot="start">
                        <IonBackButton text="Frontpage" default-href="/" />
                    </IonButtons>

                    <IonButtons slot="end">
                        {isExternalLink && (
                            <IonButton href={story?.url} target="_blank">
                                {formatUrl(story?.url!)}
                                <IonIcon slot="end" icon={openOutline} />
                            </IonButton>
                        )}
                    </IonButtons>
                </IonToolbar>
            </IonHeader>

            <IonContent color="light">
                {isPending && <IonSpinner className="my-8 w-full" />}

                {story && (
                    <>
                        <IonList className="mb-2">
                            <IonItem
                                href={isExternalLink ? story.url : undefined}
                                target="_blank"
                            >
                                <IonAvatar
                                    aria-hidden="true"
                                    slot="start"
                                    className="rounded-sm"
                                >
                                    <img
                                        alt=""
                                        src={`https://www.google.com/s2/favicons?domain=${story.url}&sz=64`}
                                    />
                                </IonAvatar>

                                <IonLabel>
                                    <h2>{story.title}</h2>
                                    <h3 className="flex items-center">
                                        {story.points}
                                        <IonIcon icon={arrowUp} />
                                        <span className="mx-2">
                                            &bull;
                                        </span>
                                        <span className="shrink-0">
                                            {relativify(story.time)}
                                        </span>
                                        {isExternalLink && (
                                            <>
                                                <span className="mx-2">
                                                    &bull;
                                                </span>
                                                <span className="truncate">
                                                    {formatUrl(story.url)}
                                                </span>
                                            </>
                                        )}
                                    </h3>
                                </IonLabel>
                            </IonItem>
                        </IonList>
                        {story.comments.map((comment) => (
                            <IonList
                                key={comment.id}
                                className="mb-2"
                            >
                                <IonItem>
                                    <IonLabel>
                                        <p
                                            onClick={() => {
                                                toggleCollapse(comment.id);
                                            }}
                                            className="flex items-center cursor-pointer"
                                        >
                                            {comment.user}
                                            <span className="mx-2">
                                                &bull;
                                            </span>
                                            {relativify(comment.time)}
                                            <span className="ml-auto">
                                                {!collapsedThreads.has(
                                                        comment.id,
                                                    )
                                                    ? (
                                                        <IonIcon
                                                            icon={chevronUp}
                                                        />
                                                    )
                                                    : (
                                                        <IonIcon
                                                            icon={chevronDown}
                                                        />
                                                    )}
                                            </span>
                                        </p>
                                        {!collapsedThreads.has(comment.id) &&
                                            (
                                                <div>
                                                    <IonText>
                                                        <div
                                                            dangerouslySetInnerHTML={{
                                                                __html: comment
                                                                    .content,
                                                            }}
                                                        />
                                                    </IonText>
                                                </div>
                                            )}
                                    </IonLabel>
                                </IonItem>
                                {!collapsedThreads.has(comment.id) &&
                                    comment.comments.map((reply: Comment) => (
                                        <IonItem
                                            key={reply.id}
                                            style={{
                                                paddingLeft:
                                                    `${reply.level}rem`,
                                            }}
                                        >
                                            <IonLabel>
                                                <p className="flex items-center">
                                                    {reply.user}
                                                    <span className="mx-2">
                                                        &bull;
                                                    </span>
                                                    {relativify(reply.time)}
                                                </p>

                                                <IonText>
                                                    <div
                                                        dangerouslySetInnerHTML={{
                                                            __html: reply
                                                                .content,
                                                        }}
                                                    />
                                                </IonText>
                                            </IonLabel>
                                        </IonItem>
                                    ))}
                            </IonList>
                        ))}
                    </>
                )}
            </IonContent>
        </IonPage>
    );
}
