// src/lib/components/StoryListing.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import type { Story } from '$lib/types';

	const { story }: { story: Story } = $props();
</script>

<a
	href={resolve('/story/[id]', { id: story.id.toString() })}
	class="rounded-2xl p-4 mb-2 grid grid-cols-[auto_1fr] gap-x-4 grid-rows-2 bg-mist-700"
>
	<img
		alt="favicon"
		class="rounded row-span-2 size-12"
		src={`https://www.google.com/s2/favicons?domain=${story.url}&sz=64`}
	/>

	<div class="title">{story.title}</div>
	<div>
		<span>{story.points} points</span>
		<span>{story.comments_count} comments</span>
	</div>
</a>

// src/components/StoryListing.tsx
import type { Story } from '@/lib/types'
import { IonAvatar, IonIcon, IonItem, IonLabel, IonNote } from '@ionic/react'
import { arrowUp } from 'ionicons/icons'
import { formatUrl, relativify } from '@/lib/utils'

export default function StoryListing({ story }: { story: Story }) {
  return (
    <IonItem
      routerLink={`/story/${story.id}`}
      draggable={false}
      detail
      className="select-none"
    >
      <IonAvatar
        aria-hidden
        slot="start"
        className="rounded-sm"
      >
        <img src={`https://www.google.com/s2/favicons?domain=${story.url}&sz=64`} />
      </IonAvatar>
      <IonLabel>
        <h2>{story.title}</h2>
        <h3 className="flex items-center">
          {story.points}
          <IonIcon icon={arrowUp} />
          <span className="mx-2">&bull;</span>
          <span className="shrink-0">{relativify(story.time)}</span>
          {story.url.startsWith('http') && (
            <>
              <span className="mx-2">&bull;</span>
              <span className="truncate">
                {formatUrl(story.url)}
              </span>
            </>
          )}
        </h3>
      </IonLabel>
      <IonNote>{story.comments_count}</IonNote>
    </IonItem>
  )
}
