// src/lib/components/StoryListing.vue
<script setup lang="ts">
  import { IonAvatar, IonIcon, IonItem, IonLabel, IonNote } from "@ionic/vue";

  import { arrowUp } from "ionicons/icons";
  import { formatUrl, relativify } from "../utils";
  import { Story } from "../types";

  defineProps<{ story: Story }>();
</script>

<template>
  <ion-item
    :router-link="`/story/${story.id}`"
    :draggable="false"
    detail
    :style="{
      userSelect: 'none',
      '-webkit-user-drag': 'none',
      '-moz-user-drag': 'none',
    }"
  >
    <ion-avatar
      aria-hidden="true"
      slot="start"
      :style="{ '--border-radius': '.25rem' }"
    >
      <img
        alt=""
        :src="`https://www.google.com/s2/favicons?domain=${story.url}&sz=64`"
      />
    </ion-avatar>
    <ion-label>
      <h2>{{ story.title }}</h2>
      <h3 style="display: flex; align-items: center">
        {{ story.score }}
        <ion-icon :icon="arrowUp" />
        <span style="margin-inline: 0.5rem">&bull;</span>
        <span style="flex-shrink: 0">{{ relativify(story.time) }}</span>
        <template v-if="story.url">
          <span style="margin-inline: 0.5rem">&bull;</span>
          <span
            style="
              white-space: nowrap;
              text-overflow: ellipsis;
              overflow: hidden;
            "
          >
            {{ formatUrl(story.url) }}
          </span>
        </template>
      </h3>
    </ion-label>
    <ion-note>{{ story.descendants }}</ion-note>
  </ion-item>
</template>

// src/components/StoryListing.tsx
import type { Story } from "@/lib/types";
import { formatUrl, relativify } from "@/lib/utils";
import { IonAvatar, IonIcon, IonItem, IonLabel, IonNote } from "@ionic/react";
import { arrowUp } from "ionicons/icons";

export default function StoryListing({ story }: { story: Story }) {
    return (
        <IonItem
            routerLink={`/story/${story.id}`}
            draggable={false}
            detail
            className="select-none"
        >
            <IonAvatar
                aria-hidden
                slot="start"
                className="rounded-sm"
            >
                <img
                    src={`https://www.google.com/s2/favicons?domain=${story.url}&sz=64`}
                />
            </IonAvatar>
            <IonLabel>
                <h2>{story.title}</h2>
                <h3 className="flex items-center">
                    {story.score}
                    <IonIcon icon={arrowUp} />
                    <span className="mx-2">&bull;</span>
                    <span className="shrink-0">{relativify(story.time)}</span>
                    {story.url.startsWith("http") && (
                        <>
                            <span className="mx-2">&bull;</span>
                            <span className="truncate">
                                {formatUrl(story.url)}
                            </span>
                        </>
                    )}
                </h3>
            </IonLabel>
            <IonNote>{story.descendants}</IonNote>
        </IonItem>
    );
}
